name: pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python 3.12 setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Docker image build
        run: docker build -t devsecops-prototype .

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: devsecops-prototype
          args: --severity-threshold=high

  owasp-zap-scan:
    runs-on: ubuntu-latest
    needs: build-test-scan
    permissions:
      issues: write
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://devsecops-pipeline-prototype.onrender.com/"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_report
          path: ./zap_report
